/* Local research only: accepted is a review decision, never operational enrollment. */
const $=id=>document.getElementById(id);
const esc=v=>String(v??'No informado').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const states={pending:'Pendiente',doubtful:'Dudosa',accepted:'Aceptada',rejected:'Rechazada'};
const stateColors={pending:'#ffdd38',doubtful:'#ed8b24',accepted:'#20934f',rejected:'#d93740'};
let D={stations:[],records:[],gaps:[],searches:[]},ready=false,terrain=false,investigate=false,busy=false,selected=null,cardSerial=0;
const availability=new Map(),inflight=new Map();
let activities=0;
function beginOnline(text){activities++;$('online-message').textContent=text;if(!$('online').open)$('online').showModal()}
function endOnline(){activities=Math.max(0,activities-1);if(!activities)$('online').close()}
$('online').addEventListener('cancel',e=>e.preventDefault());

function message(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error)}
async function api(path,body){const response=await fetch('/api/'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await response.json();if(!response.ok)throw Error(data.error||'Error al consultar el servidor local');return data}
let placeSearchSerial=0,placeMarker=null;
function markPlace(place){
  placeMarker?.remove();
  const el=document.createElement('div');el.className='place-marker';el.title=place.label;
  const name=document.createElement('span');name.textContent=place.name;el.append(name);
  // A navigation landmark only; clicking it must not investigate WU stations.
  el.addEventListener('click',e=>e.stopPropagation());
  el.addEventListener('dblclick',e=>e.stopPropagation());
  placeMarker=new maplibregl.Marker({element:el,anchor:'bottom'}).setLngLat([place.lon,place.lat]).addTo(map);
}
function closePlaces(){placeSearchSerial++;$('place-results').hidden=true}
$('place-search').onsubmit=async e=>{
  e.preventDefault();const query=$('place-query').value.trim();if(query.length<2)return;
  placeMarker?.remove();placeMarker=null;
  const serial=++placeSearchSerial,center=map.getCenter();
  $('place-results').hidden=false;$('place-options').replaceChildren();$('place-status').textContent='Buscando lugares online…';$('place-submit').disabled=true;
  try{
    const data=await api('places',{query,lat:center.lat,lon:((center.lng+180)%360+360)%360-180});
    if(serial!==placeSearchSerial)return;
    $('place-status').textContent=data.results.length?'Elige un lugar. Puedes añadir provincia o país para precisar.':'No se han encontrado lugares. Prueba otro nombre o añade la provincia.';
    for(const place of data.results){const button=document.createElement('button');button.type='button';button.textContent=place.label;button.onclick=()=>{closePlaces();markPlace(place);map.flyTo({center:[place.lon,place.lat],zoom:place.zoom});message('Lugar: '+place.label);$('place-query').focus()};$('place-options').append(button)}
  }catch(err){if(serial===placeSearchSerial)$('place-status').textContent=err.message}
  finally{$('place-submit').disabled=false}
};
$('place-search').addEventListener('keydown',e=>{if(e.key==='Escape'){closePlaces();$('place-query').focus()}});
document.addEventListener('click',e=>{if(!e.target.closest('#place-search'))closePlaces()});
const labels={'esri-satellite-vector':'Satélite+','esri-hybrid':'Híbrido','opentopomap':'Topográfico','openfreemap-liberty':'Liberty'};
const styleValue=s=>s.url||structuredClone(s.style);
const map=new maplibregl.Map({container:'map',bounds:[[0.1,40.5],[3.4,42.9]],fitBoundsOptions:{padding:35},style:styleValue(COVERAGE_BASE_STYLES[0])});
map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-left');map.addControl(new maplibregl.ScaleControl());
map.addControl({onAdd(){const el=document.createElement('div');el.className='maplibregl-ctrl maplibregl-ctrl-group view-controls';el.innerHTML='<div class="basemap-control"><button id="basemap-toggle" title="Elegir fondo del mapa" aria-label="Elegir fondo del mapa" aria-expanded="false" aria-controls="basemap-panel"><svg width="21" height="21" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 8l9-5 9 5-9 5zM3 12l9 5 9-5M3 16l9 5 9-5" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg></button><div id="basemap-panel" hidden><fieldset id="basemap"><legend>Fondo del mapa</legend></fieldset></div></div><button id="terrain" title="Activar relieve 3D" aria-label="Activar relieve 3D" aria-pressed="false">2D</button><button id="north" title="Orientar al norte" aria-label="Orientar al norte">↑N</button><button id="investigate" title="Investigar estaciones: activar y pulsar un punto" aria-label="Investigar estaciones" aria-pressed="false">⌖</button>';
el.querySelector('#terrain').onclick=()=>{terrain=!terrain;applyTerrain();map.easeTo({pitch:terrain?55:0,duration:350})};el.querySelector('#north').onclick=()=>map.easeTo({bearing:0,duration:350});el.querySelector('#investigate').onclick=()=>{investigate=!investigate;$('investigate').classList.toggle('active',investigate);$('investigate').setAttribute('aria-pressed',String(investigate));map.getCanvas().style.cursor=investigate?'crosshair':'';message(investigate?'Investigación activa: pulsa un punto libre del mapa. Hasta 10 estaciones cercanas por consulta.':'Investigación desactivada. Puedes seguir revisando las fichas.')};this.el=el;return el},onRemove(){this.el.remove()}},'top-left');
let activeBasemap=COVERAGE_BASE_STYLES[0].id;
for(const style of COVERAGE_BASE_STYLES){const label=document.createElement('label');label.className='basemap-option';const radio=document.createElement('input');radio.type='radio';radio.name='basemap-choice';radio.value=style.id;radio.checked=style.id===activeBasemap;radio.onchange=()=>chooseBasemap(style.id);label.append(radio,document.createTextNode(labels[style.id]||style.label));$('basemap').append(label)}
function closeBasemap(){ $('basemap-panel').hidden=true;$('basemap-toggle').setAttribute('aria-expanded','false') }
$('basemap-toggle').onclick=()=>{const open=$('basemap-panel').hidden;$('basemap-panel').hidden=!open;$('basemap-toggle').setAttribute('aria-expanded',String(open));if(open)$('basemap').querySelector('input:checked').focus()};
document.addEventListener('click',e=>{if(!e.target.closest('.basemap-control'))closeBasemap()});
$('basemap-panel').addEventListener('keydown',e=>{if(e.key==='Escape'){closeBasemap();$('basemap-toggle').focus()}});
function applyTerrain(){if($('terrain')){$('terrain').textContent=terrain?'3D':'2D';$('terrain').setAttribute('aria-pressed',String(terrain));$('terrain').title=terrain?'Desactivar relieve 3D':'Activar relieve 3D'}if(!ready)return;if(!terrain){map.setTerrain(null);return}if(!map.getSource('research-dem'))map.addSource('research-dem',{type:'raster-dem',tiles:COVERAGE_TERRAIN_TILES,tileSize:256,maxzoom:15,encoding:'terrarium',attribution:'Elevation tiles © Mapzen'});map.setTerrain({source:'research-dem',exaggeration:1})}
const fc=(rows,lon='lon',lat='lat')=>({type:'FeatureCollection',features:rows.map(p=>({type:'Feature',geometry:{type:'Point',coordinates:[p[lon],p[lat]]},properties:p}))});
function chosen(){const filter=$('selection').value,review=$('review').value;return D.records.filter(c=>c.kind==='candidate'&&(filter!=='short'||c.rank!=null)&&(review==='all'||review===c.review_status))}
function chosenStations(){const sources=new Set(Array.from($('station-source').querySelectorAll('input:checked'),input=>input.value));return D.stations.filter(s=>sources.has(s.source))}
function update(){const stations=chosenStations(),candidates=chosen(),pre=D.records.filter(c=>c.kind==='preliminary');if(ready){map.getSource('candidates')?.setData(fc(candidates,'longitude','latitude'));map.getSource('preliminary')?.setData(fc(pre,'longitude','latitude'));map.getSource('stations')?.setData(fc(stations));for(const id of ['gaps','searches'])map.getSource(id)?.setData(fc(D[id]));for(const id of ['stations','gaps','searches','preliminary'])map.setLayoutProperty(id,'visibility',$(id).checked?'visible':'none')}
$('station-source').disabled=!$('stations').checked;
const sourceCount=$('station-source').querySelectorAll('input:checked').length;$('source-summary').textContent='Fuentes actuales: '+(sourceCount===4?'todas':sourceCount===0?'ninguna':sourceCount+' de 4');
$('status').textContent=($('stations').checked?stations.length:0)+' actuales · '+candidates.length+' candidatas · '+($('preliminary').checked?pre.length:0)+' preliminares visibles'}
map.on('style.load',()=>{ready=true;for(const id of ['stations','gaps','searches','candidates','preliminary'])map.addSource(id,{type:'geojson',data:fc([])});
map.addLayer({id:'gaps',type:'circle',source:'gaps',paint:{'circle-radius':5,'circle-color':['case',['>',['get','nearest_km'],10],'#d73027','#ffad33'],'circle-opacity':.4}});
map.addLayer({id:'stations',type:'circle',source:'stations',paint:{'circle-radius':7,'circle-color':['match',['get','source'],'Meteocat','#0072b2','AEMET','#009e73','Meteoclimatic','#6d4c9c','#d55e00'],'circle-stroke-color':'white','circle-stroke-width':2}});
map.addLayer({id:'searches',type:'circle',source:'searches',paint:{'circle-radius':9,'circle-color':'transparent','circle-stroke-color':'black','circle-stroke-width':2}});
map.addLayer({id:'preliminary',type:'circle',source:'preliminary',paint:{'circle-radius':11,'circle-color':'#ae30c7','circle-opacity':.45,'circle-stroke-color':'#ae30c7','circle-stroke-width':3}});
map.addLayer({id:'candidates',type:'circle',source:'candidates',paint:{'circle-radius':8,'circle-color':['match',['get','review_status'],...Object.entries(stateColors).flat(),'#ffdd38'],'circle-stroke-color':'#252525','circle-stroke-width':2}});update();applyTerrain()});
map.on('error',e=>{if(e.error)message('No se ha podido cargar parte del mapa o relieve. Prueba otro fondo.',true)});
function chooseBasemap(id){closeBasemap();$('basemap-toggle').focus();if(id===activeBasemap)return;activeBasemap=id;$('basemap-toggle').title='Fondo: '+labels[id];ready=false;map.setStyle(styleValue(COVERAGE_BASE_STYLES.find(s=>s.id===id)),{diff:false})}
for(const id of ['selection','review','station-source','stations','gaps','searches','preliminary'])$(id).onchange=update;
$('clear-preliminary').onclick=async e=>{if(busy)return;e.target.disabled=true;try{const result=await api('clear-preliminary',{});const removed=new Set(D.records.filter(r=>r.kind==='preliminary').map(r=>r.stationId));D.records=D.records.filter(r=>r.kind!=='preliminary');if(selected&&!selected.current&&removed.has(selected.id))$('close').click();update();message(result.removed+' preliminares eliminadas. Candidatas y revisiones conservadas.')}catch(err){message(err.message,true)}finally{e.target.disabled=false}};
$('clear-queries').onclick=async e=>{if(busy)return;e.target.disabled=true;try{await api('clear-queries',{});D.searches=[];update();message('Puntos consultados eliminados. Estaciones y revisiones conservadas.')}catch(err){message(err.message,true)}finally{e.target.disabled=false}};
$('fit').onclick=()=>map.fitBounds([[0.1,40.5],[3.4,42.9]],{padding:35});
$('close').onclick=()=>{$('detail').hidden=true;selected=null;cardSerial++};
function replaceRecord(row){const i=D.records.findIndex(x=>x.stationId===row.stationId);if(i>=0)D.records[i]=row;else D.records.push(row);update()}
function showAvailability(a){if(!a)return '<p>No disponible en la base local. No equivale a 0/30.</p>';const dayList=[];for(let i=0;i<30;i++){const d=new Date(a.start+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+i);const key=d.toISOString().slice(0,10),valid=Object.hasOwn(a.rainfall_mm,key);dayList.push(`<span class="day ${valid?'valid':''}" title="${key}: ${valid?esc(a.rainfall_mm[key])+' mm':'sin dato'}">${key.slice(8)}</span>`)}return `<h3>Lluvia: ${a.days}/30 días con dato</h3><p>${esc(a.start)} — ${esc(a.end)}</p><div id="rain-days">${dayList.join('')}</div><dl><dt>Última lectura actual</dt><dd>${esc(a.current_reading)}</dd><dt>Último día observado en ventana</dt><dd>${esc(a.last_reading)}</dd><dt>Altitud publicada</dt><dd>${a.altitude_m==null?'No informada':esc(a.altitude_m)+' m'}</dd></dl><p class="error">${esc(a.current_error||'')}</p><p class="muted">${esc(a.origin||'Wunderground · consulta guardada '+a.fetched_at)}. Verde: dato válido, también 0 mm; gris: falta dato. Esto no valida el pluviómetro ni garantiza todo el día completo.</p>`}
function loadAvailability(id){if(availability.has(id))return Promise.resolve(availability.get(id));if(inflight.has(id))return inflight.get(id);const p=api('availability',{id}).then(a=>{availability.set(id,a);return a}).finally(()=>inflight.delete(id));inflight.set(id,p);return p}
function commonDetails(p,current){return `<dl><dt>Fuente · código</dt><dd>${current?esc(p.source):'Wunderground'} · ${esc(current?p.id:p.stationId)}</dd><dt>Coordenadas</dt><dd>${esc(current?p.lat:p.latitude)}, ${esc(current?p.lon:p.longitude)}</dd><dt>Municipio / localidad</dt><dd>${esc(p.municipality||p.stationName)}</dd>${current?`<dt>Altitud publicada</dt><dd>${esc(p.altitude_m)} m</dd><dt>Última lectura publicada</dt><dd>${esc(p.last_reading)}</dd>`:''}</dl>`}
async function showCard(p,current=false){const serial=++cardSerial;selected={id:current?p.id:p.stationId,current};$('detail').hidden=false;
$('card').innerHTML=`<h2>${esc(current?p.name:p.stationName||p.stationId)}</h2><p class="badge">${current?'Estación actual':p.kind==='preliminary'?'PRELIMINAR — recuperada online':'Candidata · '+states[p.review_status]}</p>${commonDetails(p,current)}<div id="availability">${current?showAvailability(p.availability?{...p.availability,altitude_m:p.altitude_m,current_reading:p.last_reading}:null):'Consultando los últimos 30 días completos…'}</div>${current?'':`<div id="actions"></div><p id="save-status" role="status"></p><h3>Información de investigación</h3><p>Situación en base local: ${esc(p.status)}.</p><p>QC de WU: ${esc(p.qcStatus)} (1: pasa; 0: falla; −1: no comprobado). No es nuestra aprobación.</p>${p.nearest_existing_km!=null?`<p>Red actual a ${esc(p.nearest_existing_km)} km: ${esc(p.nearest_existing_name)} (${esc(p.nearest_existing_source)}).</p>`:''}${p.rank!=null?`<p>Prioridad inicial ${esc(p.rank)}. Mejoraría ≥2 km la cobertura en ${esc(p.gap_points_improved_2km)} puntos de malla.</p>`:''}<p class="muted">Catálogo WU actualizado: ${p.updateTimeUtc?esc(new Date(p.updateTimeUtc*1000).toISOString()):'no informado'}; esta fecha no es una lectura de lluvia.</p><a target="_blank" rel="noopener" href="https://www.wunderground.com/dashboard/pws/${encodeURIComponent(p.stationId)}">Ver estación en Wunderground</a>`}`;
if(current)return;
if(p.kind==='candidate'){
$('actions').innerHTML='<label>Revisión <select id="review-card">'+Object.entries(states).map(([id,label])=>`<option value="${id}" ${id===p.review_status?'selected':''}>${label}</option>`).join('')+'</select></label><p class="muted">Guardado automático en este Mac. Aceptada no la incorpora todavía al IDW.</p>';
$('review-card').onchange=async e=>{const selector=e.target,old=p.review_status;selector.disabled=true;$('save-status').textContent='Guardando…';try{const row=await api('review',{id:p.stationId,state:selector.value});replaceRecord(row);p=row;if(serial===cardSerial){$('save-status').textContent='Guardado en disco ✓';$('card').querySelector('.badge').textContent='Candidata · '+states[row.review_status]}}catch(err){selector.value=old;if(serial===cardSerial)$('save-status').textContent='No guardado: '+err.message}finally{selector.disabled=false}};
}else{$('actions').innerHTML='<button id="promote">Promover a candidata</button><p class="muted">Conserva los datos y queda Pendiente de revisión.</p>';$('promote').disabled=['excluida','conocida'].includes(p.status);$('promote').onclick=async e=>{e.target.disabled=true;try{const row=await api('promote',{id:p.stationId});replaceRecord(row);$('selection').value='candidates';$('review').value='all';update();if(serial===cardSerial)showCard(row);message('Candidata guardada. Aún no forma parte de la red operativa.')}catch(err){if(serial===cardSerial){$('save-status').textContent=err.message;e.target.disabled=false}}}}
const showOnline=!availability.has(p.stationId);if(showOnline)beginOnline('Consultando los últimos 30 días y la lectura actual de '+p.stationId+'…');
try{const a=await loadAvailability(p.stationId);if(serial===cardSerial)$('availability').innerHTML=showAvailability(a)}catch(err){if(serial===cardSerial){$('availability').innerHTML='<p class="error">'+esc(err.message)+'</p><button id="retry">Reintentar consulta</button>';$('retry').onclick=()=>showCard(p)}}finally{if(showOnline)endOnline()}
}
map.on('click',async e=>{if(!ready)return;const hits=map.queryRenderedFeatures(e.point,{layers:['candidates','preliminary','stations']});if(hits.length){const f=hits[0];if(f.layer.id==='stations'){const p=D.stations.find(s=>s.id===f.properties.id&&s.source===f.properties.source);if(p)showCard(p,true)}else{const p=D.records.find(s=>s.stationId===f.properties.stationId);if(p)showCard(p)}return}
if(!investigate){const gap=map.queryRenderedFeatures(e.point,{layers:['gaps']})[0];if(gap)new maplibregl.Popup().setLngLat(e.lngLat).setHTML(`<b>${esc(gap.properties.municipality)}</b><p>Red actual a ${esc(gap.properties.nearest_km)} km (${esc(gap.properties.nearest_name)}).</p>`).addTo(map);return}
if(busy){message('Hay una consulta en curso. Espera a que termine.');return}busy=true;beginOnline('Buscando estaciones cercanas en Wunderground…');message('Buscando estaciones cercanas en Wunderground…');
try{const result=await api('near',{lat:e.lngLat.lat,lon:e.lngLat.lng});for(const row of result.records)replaceRecord(row);if(!D.searches.some(p=>Math.abs(p.lat-result.query.lat)<0.00001&&Math.abs(p.lon-result.query.lon)<0.00001))D.searches.push(result.query);$('preliminary').checked=true;$('searches').checked=true;update();message(`${result.records.length} estaciones recuperadas; ${result.ignored_current||0} ya incorporadas omitidas. Preliminares en violeta; pulsa su ficha para consultar X/30 y promoverlas.`);let checked=0,failed=0;for(const row of result.records){$('online-message').textContent=`Comprobando datos de lluvia: estación ${++checked} de ${result.records.length} (${row.stationId})…`;try{await loadAvailability(row.stationId)}catch{failed++}}message(`Consulta terminada: ${result.records.length} estaciones; ${result.ignored_current||0} ya incorporadas omitidas. ${failed?failed+' consultas de disponibilidad fallaron; se pueden reintentar desde la ficha.':'Disponibilidad guardada; revisa las fichas.'}`)}catch(err){message(err.message,true)}finally{busy=false;endOnline()}});
api('state').then(data=>{D=data;update();message('Guardado automático activo. Activa ⌖ para investigar nuevas estaciones.')}).catch(err=>message(err.message,true));
