services:
  rainmapper:
    build: .
    image: rainmapperha:test
    environment:
      RAINMAPPER_MODE: "once"
      RAINMAPPER_SCHEDULE_TIME: "23:50"
      RAINMAPPER_TIMEZONE: "Europe/Madrid"
      GMAP_API_KEY: ${GMAP_API_KEY}
      RAINMAPPER_DAYS_INIT: "-7"
      RAINMAPPER_DAYS_END: "0"
      RAINMAPPER_CREATE_WUNDERGROUND: "true"
      RAINMAPPER_CREATE_METEOCLIMATIC: "true"
      RAINMAPPER_CREATE_METEOCAT: "true"
      RAINMAPPER_NOMAPS: "false"
      RAINMAPPER_NOTOTALS: "false"
      RAINMAPPER_DAYS_BUCKET: "10"
      RAINMAPPER_MAX_THREADS: "1"
      RAINMAPPER_MAX_ATTEMPTS: "3"
    volumes:
      - ./docker-data/Data:/app/Data
      - ./docker-data/Tomap:/app/Tomap
      - ./docker-data/Plots:/app/Plots