// Independent GDAL-produced input, not a ring generated by the code under test.
import assert from 'node:assert/strict';
import fs from 'node:fs';
globalThis.window = {};
await import('../rainmapper-app/app/known-sites-circles.js');
const circles = window.RainmapperSiteCircles;
const original = JSON.parse(fs.readFileSync(new URL('./fixtures/known_sites_gbif_circle.json', import.meta.url)));
const snapshot = JSON.stringify(original);
const circle = circles.recognise(original);
assert.ok(circle?.geodesic);
assert.ok(Math.abs(circle.center[0] - 1.44) < 1e-9);
assert.ok(Math.abs(circle.center[1] - 42.15) < 1e-9);
assert.ok(Math.abs(circle.radiusMeters - 500 / Math.cos(Math.PI / 256)) < 0.00001);
const recreated = circles.geometry(circle);
for (let i = 0; i < original.coordinates[0].length; i++) {
  for (let axis = 0; axis < 2; axis++) assert.ok(Math.abs(original.coordinates[0][i][axis] - recreated.coordinates[0][i][axis]) < 1e-9);
}
const reversed = structuredClone(original);
reversed.coordinates[0].reverse();
assert.ok(circles.recognise(reversed)?.geodesic);
const moved = {...circle, center: [2, 43], radiusMeters: 700};
assert.ok(Math.abs(circles.recognise(circles.geometry(moved)).radiusMeters - 700) < 0.001);
assert.ok(Math.abs(circles.radiusAt(moved, circles.edge(moved)) - 700) < 0.001);
const edited = structuredClone(original);
edited.coordinates[0][10][0] += 0.00001;
assert.equal(circles.recognise(edited), null, 'An individually edited vertex must keep polygon editing');
const hole = structuredClone(original);
hole.coordinates.push(original.coordinates[0]);
assert.equal(circles.recognise(hole), null);
const unordered = structuredClone(original);
[unordered.coordinates[0][10], unordered.coordinates[0][11]] = [unordered.coordinates[0][11], unordered.coordinates[0][10]];
assert.equal(circles.recognise(unordered), null);
assert.equal(JSON.stringify(original), snapshot, 'Recognition must not mutate the original ring');
console.log('PASS GBIF circle: independent GDAL geometry, WGS84 radius/centre, roundtrip, movement and polygon safeguards');
