/* Private known-sites workspace: one WebGL map, on-demand details, explicit writes. */
(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  let data = JSON.parse($('sites-bootstrap').textContent);
  const initial = JSON.parse($('sites-initial').textContent);
  const stage = document.querySelector('.sites-stage');
  const endpoint = name => location.pathname.replace(/\/mushrooms\/known-sites\/?$/, '') + '/api/mushrooms/' + name;
  const state = {selection:null, form:null, dirty:false, editing:false, busy:false, draw:null, request:null, seq:0, previous:null};
  const keyOf = s => s && `${s.kind}:${s.id}`;
  const message = (text, error=false) => { $('sites-status-message').textContent=text; $('sites-status-message').classList.toggle('error',error); };
  function dirty(value=true) {state.dirty=value; if($('site-save-state')) $('site-save-state').textContent=value?'Cambios sin guardar':'Guardado';}
  function busy(text) {state.busy=Boolean(text);if(text){$('site-busy-text').textContent=text;$('site-busy').showModal();}else $('site-busy').close();}
  $('site-busy').addEventListener('cancel',e=>e.preventDefault());
  async function request(url,options={}) {const r=await fetch(url,options);let body;try{body=await r.json();}catch{throw Error('Respuesta no válida. Comprueba la conexión e inténtalo de nuevo.');}if(!r.ok||!body.ok)throw Error(body.error||`Error HTTP ${r.status}`);return body;}
  function dialog(id,title,text){const node=$(id);if(node.open)return Promise.resolve('cancel');if(title)$('site-confirm-title').textContent=title;if(text)$('site-confirm-text').textContent=text;return new Promise(resolve=>{const onClick=e=>{const b=e.target.closest('[data-choice]');if(b)finish(b.dataset.choice);};const cancel=e=>{e.preventDefault();finish('cancel');};function finish(v){node.close();node.removeEventListener('click',onClick);node.removeEventListener('cancel',cancel);resolve(v);}node.addEventListener('click',onClick);node.addEventListener('cancel',cancel);node.showModal();});}
  async function mayLeave(){if(state.busy)return false;if(!state.dirty)return true;const answer=await dialog('site-unsaved');if(answer==='save')return save();return answer==='discard';}
      const satelliteLayerIds=['satellite','satellite-boundary','satellite-road-outline','satellite-road','satellite-minor-road','satellite-road-label','satellite-place-label'];
      const hybridLayerIds=['hybrid-roads','hybrid-labels'];
      const style = {version:8,glyphs:'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf',sources:{
        satellite:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19,attribution:'Tiles &copy; Esri'},
        hybridRoads:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Transportation/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19,attribution:'Roads &copy; Esri'},
        hybridLabels:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19,attribution:'Labels &copy; Esri'},
        openmaptiles:{type:'vector',url:'https://tiles.openfreemap.org/planet',attribution:'OpenStreetMap contributors'},
        terrainDem:{type:'raster-dem',tiles:['https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png'],tileSize:256,maxzoom:15,encoding:'terrarium',attribution:'Elevation tiles &copy; Mapzen'},
        topo:{type:'raster',tiles:['https://a.tile.opentopomap.org/{z}/{x}/{y}.png','https://b.tile.opentopomap.org/{z}/{x}/{y}.png','https://c.tile.opentopomap.org/{z}/{x}/{y}.png'],tileSize:256,maxzoom:17,attribution:'OpenStreetMap · OpenTopoMap'}
      },layers:[
        {id:'satellite',type:'raster',source:'satellite'},
        {id:'satellite-boundary',type:'line',source:'openmaptiles','source-layer':'boundary',filter:['all',['!=',['get','maritime'],1],['<=',['get','admin_level'],6]],paint:{'line-color':'rgba(255,255,255,.78)','line-dasharray':[2,2],'line-width':['interpolate',['linear'],['zoom'],5,.7,10,1.4,14,2.2]}},
        {id:'satellite-road-outline',type:'line',source:'openmaptiles','source-layer':'transportation',filter:['match',['get','class'],['motorway','trunk','primary','secondary','tertiary'],true,false],layout:{'line-cap':'round','line-join':'round'},paint:{'line-color':'rgba(0,0,0,.75)','line-width':['interpolate',['exponential',1.2],['zoom'],6,1.4,10,2.8,15,8]}},
        {id:'satellite-road',type:'line',source:'openmaptiles','source-layer':'transportation',filter:['match',['get','class'],['motorway','trunk','primary','secondary','tertiary'],true,false],layout:{'line-cap':'round','line-join':'round'},paint:{'line-color':['match',['get','class'],['motorway','trunk'],'#f6c453',['primary'],'#ffd37a','#fff'],'line-width':['interpolate',['exponential',1.2],['zoom'],6,.8,10,1.6,15,5]}},
        {id:'satellite-minor-road',type:'line',source:'openmaptiles','source-layer':'transportation',minzoom:12,filter:['match',['get','class'],['minor','service','track'],true,false],layout:{'line-cap':'round','line-join':'round'},paint:{'line-color':'rgba(255,255,255,.86)','line-width':['interpolate',['exponential',1.2],['zoom'],12,.6,16,3.2]}},
        {id:'satellite-road-label',type:'symbol',source:'openmaptiles','source-layer':'transportation_name',minzoom:12,layout:{'symbol-placement':'line','text-field':['coalesce',['get','name_en'],['get','name']],'text-font':['Noto Sans Regular'],'text-size':['interpolate',['linear'],['zoom'],12,11,15,13]},paint:{'text-color':'#fff','text-halo-color':'rgba(0,0,0,.8)','text-halo-width':1.4}},
        {id:'satellite-place-label',type:'symbol',source:'openmaptiles','source-layer':'place',filter:['match',['get','class'],['country','state','city','town','village'],true,false],layout:{'text-field':['coalesce',['get','name_en'],['get','name']],'text-font':['Noto Sans Bold'],'text-size':['interpolate',['linear'],['zoom'],4,11,8,14,12,18],'text-max-width':9},paint:{'text-color':'#fff','text-halo-color':'rgba(0,0,0,.9)','text-halo-width':1.8}},
        {id:'hybrid-roads',type:'raster',source:'hybridRoads',layout:{visibility:'none'}},
        {id:'hybrid-labels',type:'raster',source:'hybridLabels',layout:{visibility:'none'}},
        {id:'topo',type:'raster',source:'topo',layout:{visibility:'none'}}
      ]};
  const map = new maplibregl.Map({container:'known-site-map',style,center:[1.7,41.8],zoom:7,maxPitch:85});
  map.addControl(new maplibregl.NavigationControl({showCompass:false}),'bottom-right');
  map.addControl(new maplibregl.ScaleControl({maxWidth:90,unit:'metric'}));
  let ready=false,terrain=false,loadingDraw=false,originalGeometry=null,geometryChanged=false;
  const features=()=>data.geojson.features;
  const featureFor=key=>features().find(f=>f.properties.key===key);
  function fitGeometry(g){if(!g)return;const b=new maplibregl.LngLatBounds();function visit(c){if(typeof c[0]==='number')b.extend(c);else c.forEach(visit);}visit(g.coordinates);if(!b.isEmpty())map.fitBounds(b,{padding:padding(),maxZoom:16,duration:600});}
  function padding(){const wide=innerWidth>1100;return {top:60,bottom:130,left:$('sites-list').hidden?65:(wide?305:255),right:$('sites-detail').hidden?65:(wide?390:345)};}
  function fit(g){if(innerWidth<=760){if(g?.type==='Point')map.flyTo({center:g.coordinates,zoom:14});else if(g){const b=new maplibregl.LngLatBounds();const flat=c=>typeof c[0]==='number'?b.extend(c):c.forEach(flat);flat(g.coordinates);if(!b.isEmpty())map.fitBounds(b,{padding:55,maxZoom:16});}}else fitGeometry(g);}
  function fitAll(){const fs=visibleFeatures();if(!fs.length)return;fit({type:'MultiPoint',coordinates:fs.flatMap(f=>{const pts=[];const flat=c=>typeof c[0]==='number'?pts.push(c):c.forEach(flat);flat(f.geometry.coordinates);return pts;})});}
  function normalize(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
  function matches(row){const status=$('sites-status').value, q=normalize($('sites-filter').value);const parent=data.rows.find(p=>p.kind==='area'&&p.id===row.parent);return (status==='all'||row.archived===(status==='archived'))&&(!q||normalize([row.name,row.id,parent?.name].join(' ')).includes(q));}
  function visibleFeatures(){const keys=new Set(data.rows.filter(matches).map(r=>r.key));return features().filter(f=>keys.has(f.properties.key));}
  function updateMap(){if(!ready)return;map.getSource('sites').setData({type:'FeatureCollection',features:visibleFeatures()});const key=keyOf(state.selection)||'';for(const layer of ['sites-selected-fill','sites-selected-line','sites-selected-point'])map.setFilter(layer,['all',['==',['get','key'],key],['==',['geometry-type'],layer==='sites-selected-point'?'Point':'Polygon']]);}
  function listRow(row){const button=document.createElement('button');button.type='button';button.className=`site-row ${row.kind==='micro_area'?'micro':''} ${row.archived?'archived':''} ${row.key===keyOf(state.selection)?'selected':''}`;button.dataset.siteKey=row.key;button.setAttribute('aria-current',String(row.key===keyOf(state.selection)));const name=document.createElement('span');name.textContent=row.name;const count=document.createElement('small');count.textContent=row.count;count.title='Observaciones vinculadas';button.title=[row.archived?'Archivado':'',row.has_geometry?'':'Sin polígono',row.soilgrids_pending?'SoilGrids pendiente':''].filter(Boolean).join(' · ');button.append(name,count);button.onclick=()=>select(row.kind,row.id);return button;}
  const expanded=new Set();
  function renderTree(){const root=$('sites-tree');root.replaceChildren();const sorted=[...data.rows].sort((a,b)=>a.name.localeCompare(b.name));for(const area of sorted.filter(r=>r.kind==='area')){const kids=sorted.filter(r=>r.parent===area.id&&matches(r));if(!matches(area)&&!kids.length)continue;const d=document.createElement('details');d.dataset.area=area.id;d.open=expanded.has(area.id)||state.selection?.parent===area.id||state.selection?.id===area.id||Boolean($('sites-filter').value);d.ontoggle=()=>d.open?expanded.add(area.id):expanded.delete(area.id);const summary=document.createElement('summary');const row=listRow(area);row.onclick=e=>{e.preventDefault();select(area.kind,area.id);};summary.append(row);d.append(summary);kids.forEach(k=>d.append(listRow(k)));root.append(d);}if(!root.children.length){const p=document.createElement('p');p.className='site-empty';p.textContent='No hay setales con este filtro.';root.append(p);}const active=data.rows.filter(r=>!r.archived);$('sites-counts').textContent=`${active.filter(r=>r.kind==='area').length} áreas · ${active.filter(r=>r.kind==='micro_area').length} microáreas activas`;const pending=active.filter(r=>r.soilgrids_pending).length;if(pending)$('sites-counts').textContent+=` · ${pending} SoilGrids pendientes`;updateMap();}
  function setList(open){$('sites-list').hidden=!open;stage.classList.toggle('list-closed',!open);$('sites-list-toggle').setAttribute('aria-expanded',String(open));}
  $('sites-list-toggle').onclick=()=>{const open=$('sites-list').hidden;setList(open);if(open&&innerWidth<=760)$('sites-detail').hidden=true;};
  $('sites-filter').oninput=renderTree;$('sites-status').onchange=renderTree;
  function selectionControls(){const s=state.selection,existing=s&&!s.create;$('site-archive').disabled=!existing;$('site-archive').textContent=s?.archived?'Restaurar':'Archivar';$('site-delete').hidden=!existing||!s.archived;$('site-fit-selected').disabled=!s;$('site-detail-toggle').disabled=!s;$('site-geometry-tools').hidden=!s;$('site-recover-gis').disabled=!existing;}
  function geometry(){try{return JSON.parse(state.form?.querySelector('[name=geometry_json]').value||'null');}catch{return null;}}
  function geomStatus(){const g=geometry();$('site-geometry-status').textContent=state.editing?'Editando geometría · cambios sin guardar':g?'Geometría definida':'Sin polígono · dibuja o guarda para completar más tarde';}
  function stopDrawing(){if(state.draw){loadingDraw=true;state.draw.getTerraDrawInstance().setMode('render');state.draw.getTerraDrawInstance().clear();loadingDraw=false;}state.editing=false;for(const id of ['site-draw-polygon','site-edit-polygon','site-finish-geometry','site-clear-geometry'])$(id).hidden=true;$('site-edit-geometry').hidden=false;geomStatus();}
  function syncGeometry(){if(loadingDraw||!state.editing||!state.form)return;const polygons=(state.draw.getFeatures()?.features||[]).filter(f=>f.geometry?.type==='Polygon');const g=polygons.length===1?polygons[0].geometry:polygons.length?{type:'MultiPolygon',coordinates:polygons.map(f=>f.geometry.coordinates)}:null;if(JSON.stringify(g)!==JSON.stringify(geometry())){state.form.querySelector('[name=geometry_json]').value=g?JSON.stringify(g):'';geometryChanged=true;dirty();} }
  function drawFeatures(g){if(!g)return[];return (g.type==='MultiPolygon'?g.coordinates:[g.coordinates]).map((coordinates,i)=>({type:'Feature',properties:{mode:'polygon'},geometry:{type:'Polygon',coordinates}}));}
  function startDrawing(){if(!state.form||!state.draw){message('Las herramientas de dibujo no están disponibles. Recarga la página.',true);return;}loadingDraw=true;const terra=state.draw.getTerraDrawInstance();terra.clear();const g=geometry();if(g){const results=terra.addFeatures(drawFeatures(g));if(results?.some(r=>r.valid===false)){loadingDraw=false;message('No se ha podido cargar la geometría para editar. Se conserva el polígono original.',true);return;}}state.editing=true;loadingDraw=false;terra.setMode(g?'select':'polygon');for(const id of ['site-draw-polygon','site-edit-polygon','site-finish-geometry','site-clear-geometry'])$(id).hidden=false;$('site-edit-geometry').hidden=true;geomStatus();}
  $('site-edit-geometry').onclick=startDrawing;$('site-draw-polygon').onclick=()=>state.draw?.getTerraDrawInstance().setMode('polygon');$('site-edit-polygon').onclick=()=>state.draw?.getTerraDrawInstance().setMode('select');
  $('site-finish-geometry').onclick=()=>{syncGeometry();stopDrawing();showDraft();};
  $('site-clear-geometry').onclick=async()=>{if(await dialog('site-confirm','Quitar geometría','Se retirará el polígono del borrador. Solo se aplicará al guardar; el setal y sus observaciones se conservan.')==='confirm'){state.draw.getTerraDrawInstance().clear();syncGeometry();showDraft();}};
  function showDraft(){if(!ready)return;const g=geometry();map.getSource('site-draft').setData({type:'FeatureCollection',features:g?[{type:'Feature',geometry:g,properties:{}}]:[]});}
  const environment=new Set(['altitude_min_m','altitude_max_m','altitude_source','aspect_ids','slope_notes','exposure_notes','host_ids','forest_type_ids','soil_tendency_ids','habitat_feature_ids','ecology_notes']);
  const notes=new Set(['notes','access_difficulty','access_notes','provenance_source','provenance_confidence','provenance_notes']);
  async function tab(name){document.querySelectorAll('.sites-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));state.form.hidden=name==='observations';$('site-observations').hidden=name!=='observations';if(name==='observations'){await observations(0);return;}state.form.querySelectorAll('details').forEach(d=>d.open=true);state.form.querySelectorAll('.admin-field').forEach(field=>{const input=field.querySelector('[name]'),n=input?.name;field.hidden=n==='geometry_json'||(environment.has(n)?name!=='environment':notes.has(n)?name!=='notes':name!=='general');});}
  async function observations(offset){const target=$('site-observations'),seq=state.seq;target.textContent='Cargando observaciones…';try{const q=new URLSearchParams({kind:state.selection.kind,id:state.selection.id,offset});const result=await request(endpoint('known-site-observations')+'?'+q);if(seq!==state.seq)return;target.replaceChildren();const title=document.createElement('p');title.textContent=`${result.total} observaciones vinculadas`;target.append(title);for(const r of result.items){const link=document.createElement('a');link.className='site-observation';link.href=r.href;link.textContent=r.date+' · '+r.species.replaceAll('_',' ');const small=document.createElement('small');small.textContent=r.abundance;link.append(small);link.onclick=async e=>{e.preventDefault();if(await mayLeave()){dirty(false);location.href=link.href;}};target.append(link);}for(const [text,value] of [['← Anteriores',offset>=50?offset-50:null],['Siguientes →',result.next]])if(value!==null){const b=document.createElement('button');b.textContent=text;b.onclick=()=>observations(value);target.append(b);}}catch(e){if(seq===state.seq)target.textContent=e.message;}}
  function applyFragment(fragment){stopDrawing();state.selection=fragment.selection;$('sites-detail').innerHTML=fragment.editor_html;$('sites-detail').hidden=false;state.form=$('sites-detail').querySelector('form');state.form.addEventListener('input',()=>dirty());state.form.addEventListener('change',()=>dirty());state.form.addEventListener('submit',e=>{e.preventDefault();save();});originalGeometry=geometry();geometryChanged=false;dirty(fragment.selection.dirty);document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('site-save').onclick=()=>save();$('site-cancel').onclick=()=>cancelEdit();document.querySelector('[data-close-detail]').onclick=async()=>{if(await mayLeave()){await cancelEdit(true);$('sites-detail').hidden=true;}};tab('general');selectionControls();geomStatus();renderTree();showDraft();$('sites-tree').querySelector('.selected')?.scrollIntoView({block:'nearest'});if(innerWidth<=760)setList(false);$('site-gis-review').innerHTML=fragment.gis_html||'';wireGIS();}
  function updateURL(params){const q=new URLSearchParams(params);q.set('return_to',data.return_to);history.pushState({},'',location.pathname+'?'+q);}
  async function select(kind,id,{skipGuard=false,fitMap=true,create=false,parent='',history=true}={}){if(!skipGuard&&!await mayLeave())return false;state.request?.abort();const controller=new AbortController();state.request=controller;const seq=++state.seq;message('Cargando ficha…');const q=new URLSearchParams({kind,id,return_to:data.return_to});if(create){q.set('new','1');q.set('parent',parent);}try{const fragment=await request(endpoint('known-site-detail')+'?'+q,{signal:controller.signal});if(seq!==state.seq)return false;applyFragment(fragment);if(history)updateURL(Object.fromEntries(q));if(fitMap){const g=featureFor(keyOf(state.selection))?.geometry||fragment.selection.parent_geometry;fit(g);}message(create?'Escribe el nombre y dibuja el polígono. Después pulsa Crear setal.':'Ficha lista. Los cambios se aplican al guardar.');return true;}catch(e){if(e.name!=='AbortError')message(e.message,true);return false;}}
  async function cancelEdit(skipGuard=false){if(!skipGuard&&!await mayLeave())return;const s=state.selection;dirty(false);if(s?.create){if(state.previous)await select(state.previous.kind,state.previous.id,{skipGuard:true,fitMap:false});else{stopDrawing();state.selection=null;state.form=null;$('sites-detail').hidden=true;selectionControls();updateMap();map.getSource('site-draft')?.setData({type:'FeatureCollection',features:[]});history.replaceState({},'',location.pathname);}}else if(s)await select(s.kind,s.id,{skipGuard:true,fitMap:false});}
  document.querySelectorAll('[data-new]').forEach(b=>b.onclick=async()=>{if(!await mayLeave())return;state.previous=state.selection&&!state.selection.create?{...state.selection}:null;const parent=state.selection?.kind==='area'?state.selection.id:state.selection?.parent||'';if(b.dataset.new==='micro_area'&&!data.rows.some(r=>r.kind==='area'&&!r.archived)){message('Crea primero un área para alojar la microárea.',true);return;}if(await select(b.dataset.new,'',{skipGuard:true,fitMap:false,create:true,parent})){dirty(true);state.form.querySelector('[name=name]').focus();startDrawing();}});
  async function refreshData(){const fresh=await request(endpoint('known-sites-workspace'));data={...data,...fresh.workspace};renderTree();}
  async function post(form,action){const body=new URLSearchParams(new FormData(form));if(action)body.set('known_site_action',action);body.set('save_confirmation','1');return request(location.pathname,{method:'POST',headers:{Accept:'application/json'},body});}
  async function save(){if(state.busy||!state.form)return false;if(!state.form.reportValidity()){await tab('general');state.form.reportValidity();return false;}syncGeometry();const s={...state.selection};const calc=s.kind==='micro_area'&&JSON.stringify(originalGeometry)!==JSON.stringify(geometry());busy(calc?'Guardando la microárea y recuperando datos DEM / SoilGrids. Puede tardar unos instantes.':'Guardando el setal…');let persisted=false;try{const r=await post(state.form);persisted=true;dirty(false);stopDrawing();const q=new URL(r.redirect,location.href).searchParams;await refreshData();await select(q.get('kind'),q.get('id'),{skipGuard:true,fitMap:false});message('Setal guardado.');return true;}catch(e){message((persisted?'El setal se guardó, pero no se pudo actualizar la vista. Recarga la página. ': 'No se ha guardado. ')+e.message,true);return false;}finally{busy(null);}}
  async function lifecycle(action){if(!await mayLeave())return;const s=state.selection;if(!s||s.create)return;const deleting=action==='delete',restoring=s.archived&&action==='archive';const title=deleting?'Borrar definitivamente':restoring?'Restaurar setal':'Archivar setal';const text=deleting?`Se borrará «${s.name}». Solo es posible si está archivado y no tiene observaciones ni microáreas vinculadas.`:`${title}: «${s.name}». Se comprobarán sus vínculos antes de aplicar el cambio.`;if(await dialog('site-confirm',title,text)!=='confirm')return;busy(title+'…');try{const body=new URLSearchParams({known_site_action:deleting?`delete_${s.kind}`:`toggle_${s.kind}_archive`,[s.kind==='area'?'area_id':'micro_area_id']:s.id,return_to:data.return_to});await request(location.pathname,{method:'POST',headers:{Accept:'application/json'},body});dirty(false);await refreshData();if(deleting){stopDrawing();state.selection=null;state.form=null;$('sites-detail').hidden=true;selectionControls();showDraft();updateMap();history.replaceState({},'',location.pathname);}else{if(!restoring)$('sites-status').value='all';await select(s.kind,s.id,{skipGuard:true,fitMap:false});}message(title+': completado.');}catch(e){message(e.message,true);}finally{busy(null);}}
  $('site-archive').onclick=()=>lifecycle('archive');$('site-delete').onclick=()=>lifecycle('delete');$('site-detail-toggle').onclick=()=>{$('sites-detail').hidden=!$('sites-detail').hidden;if(!$('sites-detail').hidden&&innerWidth<=760)setList(false);};
  $('site-recover-gis').onclick=async()=>{if(!state.form||state.selection.create||state.busy)return;syncGeometry();if(!geometry()){message('Dibuja un polígono antes de recuperar GIS / DEM.',true);return;}busy('Consultando GIS / DEM para esta geometría. Después podrás revisar qué datos incorporar.');try{const r=await post(state.form,'preview_gis_dem');const q=new URL(r.redirect,location.href).search;const fragment=await request(endpoint('known-site-detail')+q);applyFragment(fragment);dirty(true);location.hash='gis-dem-review';}catch(e){message(e.message,true);}finally{busy(null);}};
  function wireGIS(){document.querySelectorAll('[data-gis-select]').forEach(b=>b.onclick=()=>document.querySelectorAll('#gis-dem-review [data-gis-mode]').forEach(i=>{const mode=b.dataset.gisSelect;i.value=mode==='all'||(mode==='empty'&&i.dataset.currentEmpty==='true')?'replace':mode==='merge'&&i.querySelector('[value=merge]')?'merge':'keep';}));document.querySelector('[data-gis-cancel]')?.addEventListener('click',e=>{e.preventDefault();history.replaceState({},'',location.pathname+location.search);$('site-gis-review').replaceChildren();});document.querySelector('#gis-dem-review form')?.addEventListener('submit',async e=>{e.preventDefault();busy('Aplicando los campos seleccionados al borrador…');try{const r=await post(e.target);const fragment=await request(endpoint('known-site-detail')+new URL(r.redirect,location.href).search);applyFragment(fragment);history.replaceState({},'',location.pathname+location.search);dirty(true);message('Datos incorporados al borrador. Pulsa Guardar para conservarlos.');}catch(error){message(error.message,true);}finally{busy(null);}});}
  $('site-fit-all').onclick=fitAll;$('site-fit-selected').onclick=()=>fit(geometry()||featureFor(keyOf(state.selection))?.geometry||state.selection?.parent_geometry);
  $('site-north-toggle').onclick=()=>map.easeTo({bearing:0,duration:500});
  $('site-terrain-toggle').onclick=()=>{if(!ready)return;terrain=!terrain;map.setTerrain(terrain?{source:'terrainDem',exaggeration:1}:null);map.easeTo({pitch:terrain?48:0,duration:600});$('site-terrain-toggle').textContent=terrain?'2D':'3D';$('site-terrain-toggle').setAttribute('aria-pressed',String(terrain));};
  $('site-layer-toggle').onclick=()=>{$('site-layer-panel').hidden=!$('site-layer-panel').hidden;$('site-layer-toggle').setAttribute('aria-expanded',String(!$('site-layer-panel').hidden));$('site-search-panel').hidden=true;};
  document.querySelectorAll('[data-basemap]').forEach(b=>b.onclick=()=>{const topo=b.dataset.basemap==='topographic',hybrid=b.dataset.basemap==='hybrid';satelliteLayerIds.forEach((id,i)=>map.setLayoutProperty(id,'visibility',topo||(hybrid&&i>0)?'none':'visible'));hybridLayerIds.forEach(id=>map.setLayoutProperty(id,'visibility',hybrid?'visible':'none'));map.setLayoutProperty('topo','visibility',topo?'visible':'none');document.querySelectorAll('[data-basemap]').forEach(x=>x.classList.toggle('active',x===b));$('site-layer-panel').hidden=true;$('site-layer-toggle').setAttribute('aria-expanded','false');});
  // Same Photon navigation behavior as the prediction viewer: explicit submit,
  // bounded cache, cancellation, safe labels and a single replaceable POI.
  let placeMarker=null,placeController=null,lastSearch=0;const placeCache=new Map();
  function closeSearch(){$('site-search-panel').hidden=true;$('site-search-toggle').setAttribute('aria-expanded','false');placeController?.abort();}
  $('site-search-toggle').onclick=()=>{if(!$('site-search-panel').hidden){closeSearch();return;}$('site-search-panel').hidden=false;$('site-layer-panel').hidden=true;$('site-search-toggle').setAttribute('aria-expanded','true');$('site-search-input').focus();};
  $('site-search-panel').onkeydown=e=>{if(e.key==='Escape'){closeSearch();$('site-search-toggle').focus();}};
  $('site-search-form').onsubmit=async e=>{e.preventDefault();const q=$('site-search-input').value.trim().replace(/\s+/g,' ');if(q.length<2||q.length>160)return;placeMarker?.remove();placeMarker=null;placeController?.abort();const controller=new AbortController();placeController=controller;const c=map.getCenter();const params=new URLSearchParams({q,limit:'8',lat:c.lat.toFixed(1),lon:((((c.lng+180)%360+360)%360)-180).toFixed(1)});$('site-search-results').replaceChildren();$('site-search-status').textContent='Consultando lugares online…';const submit=e.target.querySelector('button');submit.disabled=true;const timeout=setTimeout(()=>controller.abort(),20000);try{let rows=placeCache.get(params.toString());if(!rows){await new Promise(r=>setTimeout(r,Math.max(0,1000-(Date.now()-lastSearch))));if(controller.signal.aborted)return;lastSearch=Date.now();const response=await fetch('https://photon.komoot.io/api/?'+params,{signal:controller.signal,credentials:'omit'});if(!response.ok)throw Error('No se pudo consultar el buscador.');const result=await response.json();if(!Array.isArray(result.features))throw Error('Respuesta no válida del buscador.');rows=result.features.slice(0,8).flatMap(f=>{const p=f.properties,g=f.geometry;if(!p||g?.type!=='Point'||!Array.isArray(g.coordinates))return[];const [lon,lat]=g.coordinates;if(!Number.isFinite(lon)||!Number.isFinite(lat)||Math.abs(lon)>180||Math.abs(lat)>90)return[];const names=[...new Set(['name','city','county','state','country'].map(k=>p[k]).filter(v=>typeof v==='string'&&v.trim()))];return names.length?[{name:names[0],label:names.join(' · '),lon,lat,zoom:({country:5,state:8,county:10,city:12})[p.type]||14}]:[];});if(placeCache.size>=50)placeCache.delete(placeCache.keys().next().value);placeCache.set(params.toString(),rows);}if(controller.signal.aborted||placeController!==controller)return;$('site-search-status').textContent=rows.length?'Selecciona un lugar.':'No se han encontrado lugares.';for(const place of rows){const b=document.createElement('button');b.type='button';b.textContent=place.label;b.onclick=()=>{closeSearch();placeMarker?.remove();const node=document.createElement('div');node.className='sites-place-marker';node.textContent=place.name;for(const ev of ['click','dblclick','pointerdown','touchstart'])node.addEventListener(ev,e=>e.stopPropagation());placeMarker=new maplibregl.Marker({element:node,anchor:'bottom'}).setLngLat([place.lon,place.lat]).addTo(map);map.flyTo({center:[place.lon,place.lat],zoom:place.zoom,duration:800});$('site-search-input').blur();};$('site-search-results').append(b);}}catch(error){if(placeController===controller&&!$('site-search-panel').hidden)$('site-search-status').textContent='No se pudo completar la búsqueda. Inténtalo de nuevo.';}finally{clearTimeout(timeout);if(placeController===controller){submit.disabled=false;placeController=null;}}};
  map.on('load',()=>{
    ready=true;
    map.addSource('sites',{type:'geojson',data:data.geojson});
    const color=['match',['get','kind'],'area','#ffc45e','#38d4b2'];
    map.addLayer({id:'sites-fill',type:'fill',source:'sites',filter:['==',['geometry-type'],'Polygon'],paint:{'fill-color':color,'fill-opacity':0.14}});
    map.addLayer({id:'sites-line',type:'line',source:'sites',filter:['==',['geometry-type'],'Polygon'],paint:{'line-color':color,'line-width':2}});
    map.addLayer({id:'sites-point',type:'circle',source:'sites',filter:['==',['geometry-type'],'Point'],paint:{'circle-color':color,'circle-radius':6,'circle-stroke-color':'#fff','circle-stroke-width':2}});
    map.addLayer({id:'sites-selected-fill',type:'fill',source:'sites',filter:['==',['get','key'],''],paint:{'fill-color':'#15a9f1','fill-opacity':0.28}});
    map.addLayer({id:'sites-selected-line',type:'line',source:'sites',filter:['==',['get','key'],''],paint:{'line-color':'#3abfff','line-width':4}});
    map.addLayer({id:'sites-selected-point',type:'circle',source:'sites',filter:['==',['get','key'],''],paint:{'circle-color':'#15a9f1','circle-radius':9,'circle-stroke-color':'#fff','circle-stroke-width':3}});
    map.addSource('site-draft',{type:'geojson',data:{type:'FeatureCollection',features:[]}});
    map.addLayer({id:'site-draft-line',type:'line',source:'site-draft',paint:{'line-color':'#40bcff','line-width':3,'line-dasharray':[2,1]}});
    try{state.draw=new MaplibreTerradrawControl.MaplibreTerradrawControl({modes:['render','polygon','select'],open:false});map.addControl(state.draw,'bottom-left');const terra=state.draw.getTerraDrawInstance();terra.setMode('render');terra.on('change',()=>{if(!loadingDraw){syncGeometry();showDraft();}});}catch(error){message('El mapa está disponible, pero no se pudieron cargar las herramientas de dibujo.',true);}
    renderTree();if(initial?.selected){applyFragment(initial);fit(featureFor(keyOf(initial.selection))?.geometry||initial.selection.parent_geometry);if(initial.gis_html)location.hash='gis-dem-review';}else fitAll();
  });
  map.on('click',e=>{if(!ready||state.editing||state.busy)return;closeSearch();$('site-layer-panel').hidden=true;$('site-overlaps').hidden=true;const found=map.queryRenderedFeatures(e.point,{layers:['sites-fill','sites-point']});const keys=[...new Set(found.map(f=>f.properties.key))];const rows=keys.map(k=>data.rows.find(r=>r.key===k)).filter(Boolean).sort((a,b)=>(a.kind==='micro_area'?-1:1)-(b.kind==='micro_area'?-1:1));if(rows.length===1)select(rows[0].kind,rows[0].id,{fitMap:false});else if(rows.length>1){const panel=$('site-overlaps');panel.replaceChildren();const heading=document.createElement('strong');heading.textContent='Selecciona un setal';panel.append(heading);rows.forEach(r=>{const b=document.createElement('button');b.textContent=`${r.kind==='area'?'Área':'Microárea'} · ${r.name}`;b.onclick=()=>{panel.hidden=true;select(r.kind,r.id,{fitMap:false});};panel.append(b);});panel.hidden=false;}});
  map.on('mousemove',e=>{if(!ready||state.editing)return;map.getCanvas().style.cursor=map.queryRenderedFeatures(e.point,{layers:['sites-fill','sites-point']}).length?'pointer':'';});
  window.addEventListener('beforeunload',e=>{if(state.dirty||state.busy){e.preventDefault();e.returnValue='';}});
  window.addEventListener('popstate',async()=>{const q=new URLSearchParams(location.search);if(q.get('id')===state.selection?.id&&q.get('kind')===state.selection?.kind)return;if(q.has('id')){if(!await select(q.get('kind'),q.get('id'),{history:false})&&state.selection)updateURL({kind:state.selection.kind,id:state.selection.id});}});
  document.querySelector('.sites-heading a').onclick=async e=>{e.preventDefault();const href=e.currentTarget.href;if(await mayLeave()){dirty(false);location.href=href;}};
  if(innerWidth<=760)setList(false);
  new ResizeObserver(()=>map.resize()).observe(stage);
  renderTree();
})();
